// Admin Login
export const AUTH_ADMIN_LOGIN_INIT = 'AUTH_ADMIN_LOGIN_INIT';
export const AUTH_ADMIN_LOGIN_LOADING = 'AUTH_ADMIN_LOGIN_LOADING';
export const AUTH_ADMIN_LOGIN_ERROR = 'AUTH_ADMIN_LOGIN_ERROR';
export const AUTH_ADMIN_LOGIN_SUCCESSFUL = 'AUTH_ADMIN_LOGIN_SUCCESSFUL';

// Sign up
export const AUTH_SIGNUP_INIT = 'AUTH_SIGNUP_INIT';
export const AUTH_LOADING_SIGNUP = 'AUTH_LOADING_SIGNUP';
export const AUTH_ERROR_SIGNUP = 'AUTH_ERROR_SIGNUP';
export const AUTH_SUCCESSFUL_SIGNUP = 'AUTH_SUCCESSFUL_SIGNUP';

// 3rd party login
export const AUTH_SIGNUP_THIRD_PARTY = 'AUTH_SIGNUP_THIRD_PARTY';

// Login
export const AUTH_LOGIN_INIT = 'AUTH_LOGIN_INIT';
export const AUTH_LOADING_LOGIN = 'AUTH_LOADING_LOGIN';
export const AUTH_ERROR_LOGIN = 'AUTH_ERROR_LOGIN';
export const AUTH_SUCCESSFUL_LOGIN = 'AUTH_SUCCESSFUL_LOGIN';

// Tokens
export const TOKENS = 'TOKENS';

// logout
export const LOGOUT = 'LOGOUT';

// Admin Product Category
export const PROD_CATEGORY_LOADING = 'PRODUCT_CATEGORY_LOADING';
export const SUBMIT_PROD_CATEGORY = 'PRODUCT_CATEGORY_SUCCESSFUL';
export const FETCH_PROD_CATEGORY = 'FETCH_PROD_CATEGORY';

export const PROD_CATEGORY_UPDATED = 'PROD_CATEGORY_UPDATED';
export const PROD_CATEGORY_DELETED = 'PROD_CATEGORY_DELETED';
