// Sign up
export const AUTH_SIGNUP_INIT = 'AUTH_SIGNUP_INIT';
export const AUTH_LOADING_SIGNUP = 'AUTH_LOADING_SIGNUP';
export const AUTH_ERROR_SIGNUP = 'AUTH_ERROR_SIGNUP';
export const AUTH_SUCCESSFUL_SIGNUP = 'AUTH_SUCCESSFUL_SIGNUP';

// Login
export const AUTH_LOGIN_INIT = 'AUTH_LOGIN_INIT';
export const AUTH_LOADING_LOGIN = 'AUTH_LOADING_LOGIN';
export const AUTH_ERROR_LOGIN = 'AUTH_ERROR_LOGIN';
export const AUTH_SUCCESSFUL_LOGIN = 'AUTH_SUCCESSFUL_LOGIN';

// Tokens
export const TOKENS = 'TOKENS';

// logout
export const LOGOUT = 'LOGOUT';
